name: Python Lint and License Check

on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Lint with flake8
      run: |
        # fail if there are any flake8 errors
        pip install flake8
        flake8 .

#    - name: Type check with MyPy
#      run: |
#        # fail if there are any MyPy errors
#        pip install mypy
#        mypy ./dubbo

  check-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check License Header
        uses: apache/skywalking-eyes/header@main
        with:
          log: info
          config: .licenserc.yaml